name: iap_app
description: Application for information aggregation platform.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^4.0.0
  html: ^0.15.0
  json_annotation: ^4.0.1
  # 动画
  flare_flutter: ^2.0.3
  flustars: ^0.3.3
  # 下拉刷新
  pull_to_refresh: ^2.0.0

  # 响应式编程 https://github.com/ReactiveX/rxdart
  rxdart: ^0.24.1

  # 下拉刷新2
  flutter_easyrefresh: ^2.2.1

  # 全局数据存储，类vuex
  provider: ^5.0.0

  # 本地存储
  shared_preferences: ^2.0.5

  # 微信登录
  # fluwx: ^1.1.1

  # # 网络图片缓存
  # cached_network_image: ^1.1.2+1
  cached_network_image: ^2.5.0

  flutter_cache_manager: ^2.1.1

  # 图片预览
  photo_view: ^0.11.1
  # 
  flutter_screenutil: ^2.3.1
  #  flutter_screenutil: ^4.0.3+1


  # 权限管理
  permission_handler: ^5.1.0+2

  # 图片选择与下载
  image_picker_saver: ^0.3.0

  image_gallery_saver: ^1.6.8

  # 单图选择
  image_picker: ^0.7.4

  # 扩展图片预览
  extended_image: ^4.0.1
  # 图片裁剪
  image_crop: ^0.3.4

  # toast
  fluttertoast: ^7.1.8
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.3.2
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^2.0.4

  # 键盘增强工具
  keyboard_actions: ^3.4.0

  common_utils: ^2.0.2

  # fluro路由
  fluro: ^1.7.8

  # 加载动画
  flutter_spinkit: ^4.1.2+1

  # 图片多选
#  photo: ^0.5.0-dev.3

  multi_image_picker: ^4.8.0

  # 加密库
  crypto: ^3.0.1

  # uuid
  uuid: ^3.0.4

  # 加载模态框
  modal_progress_hud: ^0.1.3

  # 地区选择
  city_pickers: ^0.2.0

  # 日期选择
#  flutter_datetime_picker: 1.5.1
  flutter_datetime_picker:
    git:
      url: https://github.com/Realank/flutter_datetime_picker.git
      ref: master

  # 极光推送
  jpush_flutter: ^2.0.5
  #  jpush_flutter:
  #    git:
  #      url: git://github.com/jpush/jpush-flutter-plugin.git
  #      ref: master

  # 设备信息
  device_info: ^0.4.2+8

  #  # 震动反馈
  #  vibrate: ^0.0.4

  # 小红点
  badges: ^2.0.1

  # 侧滑菜单
  #  flutter_slidable: ^0.5.4

  # 自定义文本溢出 https://github.com/fluttercandies/extended_text/blob/master/README-ZH.md
  extended_text: ^6.0.4

  flutter_svg: ^0.22.0

  # social 
  # sharesdk: ^1.1.8

  # floating action bar
  unicorndial: ^1.1.5

  # 轮播图 https://github.com/jzoom/flutter_swiper
  flutter_swiper: ^1.1.6

  install_plugin: ^2.0.1


  # 底部导航栏
  #  fancy_bar: ^1.2.0



  #
  transparent_image: ^1.0.0

#  umeng_analytics_plugin: ^1.0.3

  # 九宫格图片 https://github.com/flutterchina/nine_grid_view
  nine_grid_view: ^1.0.7

  # ws连接 https://pub.dev/packages/web_socket_channel/install
  web_socket_channel: ^1.2.0

  stomp_dart_client: ^0.3.8

  # 事件总线
  event_bus: ^1.1.1

  # 瀑布流
  flutter_staggered_grid_view: ^0.3.4

  # 提取图像主色
  palette_generator: ^0.2.3

  # 根据背景色获得字体颜色
  flutter_statusbarcolor: ^0.2.3

  # 虚线container边框
  dotted_border: ^2.0.0

  # bloc 状态管理
  flutter_bloc: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^4.1.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: PingFang
      fonts:
        - asset: assets/fonts/PingFangTC-Thin.ttf
          weight: 300
        - asset: assets/fonts/PingFangTC-Light.ttf
          weight: 400
        - asset: assets/fonts/PingFangTC.ttf
          weight: 500
  assets:
    - assets/images/
    - assets/fonts/
    - assets/images/tab/
    - assets/images/guide/
    - assets/flrs/
    - assets/svgs/
    - assets/icons/
    - assets/icons/nav/
    - assets/icons/notification/
    - assets/icons/profile/
    - assets/icons/tweet/
    - assets/icons/circle/


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
